package com.example.util

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val nativeName: String,
    val flag: String
) {
    AMHARIC("am", "Amharic", "አማርኛ", "🇪🇹"),
    AFAAN_OROMOO("om", "Afaan Oromoo", "Afaan Oromoo", "🇪🇹"),
    TIGRINYA("ti", "Tigrinya", "ትግርኛ", "🇪🇹"),
    SOMALI("so", "Somali", "Somaali", "🇸🇴"),
    ENGLISH("en", "English", "English", "🇬🇧");

    companion object {
        fun fromCode(code: String): AppLanguage {
            return values().find { it.code == code } ?: AMHARIC
        }
    }
}

data class IdCardLabels(
    val cardTitle: String,
    val nameLabel: String,
    val idLabel: String,
    val sexLabel: String,
    val dobLabel: String,
    val addressLabel: String,
    val phoneLabel: String,
    val renewalLabel: String,
    val expiryLabel: String,
    val emergencyLabel: String,
    val bloodTypeLabel: String,
    val packageTypeLabel: String,
    val sealLabel: String,
    val signatureLabel: String,
    val backHeader: String,
    val legalDisclaimer: String
)

data class AppUiLabels(
    val appTitle: String,
    val subTitle: String,
    val homeNav: String,
    val newIdNav: String,
    val paymentNav: String,
    val previewNav: String,
    val adminNav: String,
    val qrNav: String,
    val notifNav: String,
    val createNewIdBtn: String,
    val selectLanguage: String,
    val fullNameAmharicLabel: String,
    val fullNameEnglishLabel: String,
    val regionLabel: String,
    val zoneSubCityLabel: String,
    val woredaLabel: String,
    val kebeleLabel: String,
    val houseNoLabel: String,
    val phoneLabel: String,
    val emergencyContactLabel: String,
    val dobLabel: String,
    val genderLabel: String,
    val bloodTypeLabel: String,
    val renewalDateLabel: String,
    val expiryRuleNotice: String,
    val selectPackageLabel: String,
    val digitalCopyLabel: String,
    val hardcopyLabel: String,
    val submitBtn: String,
    val payNowBtn: String,
    val viewCardBtn: String,
    val filterAll: String,
    val filterPending: String,
    val filterApproved: String,
    val adminSwitchCustomer: String,
    val customerSwitchAdmin: String
)

object LanguageUtils {

    fun getIdLabels(languageCode: String): IdCardLabels {
        return when (languageCode) {
            "om" -> IdCardLabels(
                cardTitle = "Waraqaa Eenyummaa Gandaa / Resident ID",
                nameLabel = "Maqaa Guutuu / Full Name",
                idLabel = "Lakk. Eenyummaa / ID No.",
                sexLabel = "Saala / Sex",
                dobLabel = "Guyyaa Dhalootaa / Date of Birth",
                addressLabel = "Teessoo / Address",
                phoneLabel = "Lakk. Bilbilaa / Phone No.",
                renewalLabel = "Guyyaa Haaraomfame / Renewal Date",
                expiryLabel = "Guyyaa Dhumaa / Expiration Date",
                emergencyLabel = "Quunnamsiisaa Yeroo Balaa / Emergency Contact",
                bloodTypeLabel = "Gosa Dhiigaa / Blood Type",
                packageTypeLabel = "Pakeejii Kaardii / Package",
                sealLabel = "Chaappaa Gandaa",
                signatureLabel = "Mallattoo Bulchaa / Admin Signature",
                backHeader = "Waraqaa Eenyummaa Dhijitaalaa (Duba)",
                legalDisclaimer = "Waraqaan eenyummaa kun qabeenya seeraa gandaati. Yoo argame gara kuusaa poolisii ykn ganda dhiyootti deebisaa. Seeraan ala qopheessuun seeraan nama gaafachiisa."
            )
            "ti" -> IdCardLabels(
                cardTitle = "ወረቐት መንነት ቀበሌ / Resident ID",
                nameLabel = "ምሉእ ስም / Full Name",
                idLabel = "ቑፅሪ መነፅር / ID No.",
                sexLabel = "ፆታ / Sex",
                dobLabel = "ዕለት ልደት / Date of Birth",
                addressLabel = "ኣድራሻ / Address",
                phoneLabel = "ቑፅሪ ስልኪ / Phone No.",
                renewalLabel = "ዝታደሰሉ መዓልቲ / Renewal Date",
                expiryLabel = "ዘብቅዓሉ መዓልቲ / Expiration Date",
                emergencyLabel = "ህፁፅ መተሓሳሰቢ / Emergency Contact",
                bloodTypeLabel = "ዓይነት ደም / Blood Type",
                packageTypeLabel = "ዓይነት ፓኬጅ / Package",
                sealLabel = "ማህተም ቀበሌ",
                signatureLabel = "ፊርማ ምምህዳር / Admin Signature",
                backHeader = "ዲጂታል ወረቐት መንነት ኢትዮጵያ (ድሕሪት)",
                legalDisclaimer = "እዚ ወረቐት መንነት ናይ ቀበሌ ሕጋዊ ንብረት እዩ። እንተረኺብኩም ንናይ ጥቓኹም ፖሊስ ወይ ቀበሌ ሃቡ። ብዘይሕጋዊ መንገዲ ምድላው ብሕጊ የሕትት።"
            )
            "so" -> IdCardLabels(
                cardTitle = "Kaadhka Degmada / Resident ID",
                nameLabel = "Magaca Buuxa / Full Name",
                idLabel = "Tirada AQ / ID No.",
                sexLabel = "Jinsiga / Sex",
                dobLabel = "Taariikhda Dhalashada / Date of Birth",
                addressLabel = "Ciwaanka / Address",
                phoneLabel = "Nambarka Telefoonka / Phone No.",
                renewalLabel = "Taariikhda Cusbooneysiinta / Renewal Date",
                expiryLabel = "Taariikhda Dhicitaanka / Expiration Date",
                emergencyLabel = "Xiriirka Degdega / Emergency Contact",
                bloodTypeLabel = "Nooca Dhiigga / Blood Type",
                packageTypeLabel = "Cududda Kaadhka / Package",
                sealLabel = "Shaabad Degmada",
                signatureLabel = "Saxeexa Maamulaha / Admin Signature",
                backHeader = "Kaadhka Aquunsiga Dijitaalka Ah (Astaanta)",
                legalDisclaimer = "Kaadhkani wuxuu leeyahay degmada. Haddii aad hesho, fadlan ku wareeji saldhigga booliska ama degmada ugu dhow. Samaynta sharcidarrada ah waa la ciqaabaa."
            )
            "en" -> IdCardLabels(
                cardTitle = "Kebele Resident ID / የቀበሌ መታወቂያ",
                nameLabel = "Full Name / ሙሉ ስም",
                idLabel = "ID Number / መታወቂያ ቁጥር",
                sexLabel = "Sex / ፆታ",
                dobLabel = "Date of Birth / የትውልድ ቀን",
                addressLabel = "Address / አድራሻ",
                phoneLabel = "Phone No. / ስልክ ቁጥር",
                renewalLabel = "Renewal Date / የታደሰበት",
                expiryLabel = "Expiration Date / የሚያበቃበት",
                emergencyLabel = "Emergency Contact / የቅርብ ተጠሪ",
                bloodTypeLabel = "Blood Type / የደም ዓይነት",
                packageTypeLabel = "Package / የካርድ ጥቅል",
                sealLabel = "Kebele Stamp / ማህተም",
                signatureLabel = "Administrator Signature / ፊርማ",
                backHeader = "Ethiopia Digital ID Card (Back Side)",
                legalDisclaimer = "This ID card is legal property of the Kebele Administration. If found, please return to the nearest Police Station or Kebele office. Illegal forgery is punishable by law."
            )
            else -> IdCardLabels( // Amharic 'am' default
                cardTitle = "የቀበሌ ነዋሪነት መታወቂያ / Resident ID",
                nameLabel = "ሙሉ ስም / Full Name",
                idLabel = "መታወቂያ ቁጥር / ID No.",
                sexLabel = "ፆታ / Sex",
                dobLabel = "የትውልድ ቀን / Date of Birth",
                addressLabel = "አድራሻ / Address",
                phoneLabel = "ስልክ ቁጥር / Phone No.",
                renewalLabel = "የታደሰበት / Renewal Date",
                expiryLabel = "የሚያበቃበት / Expiration Date",
                emergencyLabel = "የቅርብ ተጠሪ / Emergency Contact",
                bloodTypeLabel = "የደም ዓይነት / Blood Type",
                packageTypeLabel = "የካርድ ጥቅል / Package",
                sealLabel = "የቀበሌ ማህተም",
                signatureLabel = "የአስተዳዳሪው ፊርማ / Admin Signature",
                backHeader = "የኢትዮጵያ ዲጂታል መታወቂያ (የጀርባ ገፅ)",
                legalDisclaimer = "ይህ መታወቂያ የቀበሌው ህጋዊ ንብረት ነው። ከተገኘ እባክዎ ለአቅራቢያው ፖሊስ ጣቢያ ወይም ቀበሌ ያስረክቡ። በህገ-ወጥ መንገድ ማዘጋጀት በህግ ያስቀጣል።"
            )
        }
    }

    fun getUiLabels(languageCode: String): AppUiLabels {
        return when (languageCode) {
            "om" -> AppUiLabels(
                appTitle = "Waraqaa Eenyummaa Itoophiyaa",
                subTitle = "Tajaajila Waraqaa Eenyummaa Dijitaalaa",
                homeNav = "Fuula Duraa",
                newIdNav = "Waraqaa Haaraa / Haaraomsaa",
                paymentNav = "Mirkaneessa Kaffaltii",
                previewNav = "Dur-agarsiisa Kaardii",
                adminNav = "Gulaaltuu Bulchiinsaa",
                qrNav = "Mirkaneessa Sakatta'aa QR",
                notifNav = "Ergaawwan",
                createNewIdBtn = "Waraqaa Eenyummaa Haaraa Gaafadhu",
                selectLanguage = "Afaan Filadhu",
                fullNameAmharicLabel = "Maqaa Guutuu (Afaan Naannoo)",
                fullNameEnglishLabel = "Maqaa Guutuu (Afaan Ingilizaatiin)",
                regionLabel = "Naannoo",
                zoneSubCityLabel = "Godina / Kutaa Magaalaa",
                woredaLabel = "Aanaa",
                kebeleLabel = "Ganda",
                houseNoLabel = "Lakk. Manaa",
                phoneLabel = "Lakk. Bilbilaa",
                emergencyContactLabel = "Quunnamsiisaa Yeroo Balaa",
                dobLabel = "Guyyaa Dhalootaa",
                genderLabel = "Saala",
                bloodTypeLabel = "Gosa Dhiigaa",
                renewalDateLabel = "Guyyaa Haaraomfame",
                expiryRuleNotice = "Guyyaan dhumaa waggaa 1 booda ofumaan shallagama (+1 Waggaa).",
                selectPackageLabel = "Pakeejii Kaffaltii Filadhu",
                digitalCopyLabel = "Koppii Dijitaalaa (PDF/JPG - 50 ETB)",
                hardcopyLabel = "Maxxansa Waraqaa Hardcopy (400 ETB)",
                submitBtn = "Iyyannoo Ergi & Kaffaltii Inni Boodaa",
                payNowBtn = "Kaffaltii Mirkaneessi",
                viewCardBtn = "Kaardii Ilaali",
                filterAll = "Hunda",
                filterPending = "Qorannoo Pr",
                filterApproved = "Mirkanaa'e",
                adminSwitchCustomer = "Gara Maamilatti Jijjiiri",
                customerSwitchAdmin = "Gara Bulchiinsaatti Jijjiiri"
            )
            "ti" -> AppUiLabels(
                appTitle = "ወረቐት መንነት ኢትዮጵያ",
                subTitle = "ኣገልግሎት ዲጂታል ወረቐት መንነት",
                homeNav = "ዋና ገፅ",
                newIdNav = "ሓድሽ ወረቐት መንነት / ሕድሳት",
                paymentNav = "ምረጋገፂ ክፍሊት",
                previewNav = "ቅድመ-ርእይቶ ወረቐት መንነት",
                adminNav = "መቆፃፀሪ ምምህዳር",
                qrNav = "መርመርቲ QR ኮድ",
                notifNav = "መልእኽትታት",
                createNewIdBtn = "ሓድሽ ወረቐት መንነት ሕተት",
                selectLanguage = "ቋንቋ ምረፅ",
                fullNameAmharicLabel = "ምሉእ ስም (ብቋንቋ ክልል)",
                fullNameEnglishLabel = "ምሉእ ስም (ብእንግሊዝኛ)",
                regionLabel = "ክልል",
                zoneSubCityLabel = "ዞባ / ክፍለ ከተማ",
                woredaLabel = "ወረዳ",
                kebeleLabel = "ቀበሌ",
                houseNoLabel = "ቑፅሪ ገዛ",
                phoneLabel = "ቑፅሪ ስልኪ",
                emergencyContactLabel = "ህፁፅ መተሓሳሰቢ",
                dobLabel = "ዕለት ልደት",
                genderLabel = "ፆታ",
                bloodTypeLabel = "ዓይነት ደም",
                renewalDateLabel = "ዝታደሰሉ መዓልቲ",
                expiryRuleNotice = "ዘብቅዓሉ መዓልቲ ድሕሪ 1 ዓመት ብባዕሉ ይሕሰብ (+1 ዓመት)።",
                selectPackageLabel = "ዓይነት ፓኬጅ ክፍሊት ምረፅ",
                digitalCopyLabel = "ዲጂታል ኮፒ (PDF/JPG - 50 ETB)",
                hardcopyLabel = "ሕትመት ወረቐት Hardcopy (400 ETB)",
                submitBtn = "ሕቶ ኣእትው & ናብ ክፍሊት ሕለፍ",
                payNowBtn = "ክፍሊት አረጋግፅ",
                viewCardBtn = "ወረቐት መንነት ርአ",
                filterAll = "ኩሎም",
                filterPending = "ኣብ ምፅራይ",
                filterApproved = "ዝፀደቐ",
                adminSwitchCustomer = "ናብ ተጠቃሚ ቀይር",
                customerSwitchAdmin = "ናብ ምምህዳር ቀይር"
            )
            "so" -> AppUiLabels(
                appTitle = "Kaadhka Eenyummaa Itoobiya",
                subTitle = "Astaanta Kaadhka Aqoonsiga Dijitaalka",
                homeNav = "Bogga Hore",
                newIdNav = "Kaadh Cusub / Cusbooneysiin",
                paymentNav = "Xaqiijinta Bixinta",
                previewNav = "Muujinta Kaadhka",
                adminNav = "Maamulka Guud",
                qrNav = "Baaraha QR Code",
                notifNav = "Farriimaha",
                createNewIdBtn = "Ccodso Kaadhka Cusub",
                selectLanguage = "Dooro Luqadda",
                fullNameAmharicLabel = "Magaca Buuxa (Luqadda Gobolka)",
                fullNameEnglishLabel = "Magaca Buuxa (Ingiriisi)",
                regionLabel = "Gobolka",
                zoneSubCityLabel = "Aagga / Dagmada",
                woredaLabel = "Woreda",
                kebeleLabel = "Kebele",
                houseNoLabel = "Nambarka Guriga",
                phoneLabel = "Nambarka Telefoonka",
                emergencyContactLabel = "Xiriirka Degdega",
                dobLabel = "Taariikhda Dhalashada",
                genderLabel = "Jinsiga",
                bloodTypeLabel = "Nooca Dhiigga",
                renewalDateLabel = "Taariikhda Cusbooneysiinta",
                expiryRuleNotice = "Taariikhda dhicitaanka wuxuu si iskiis ah u xisaabiyaa 1 sano ka dib (+1 Sano).",
                selectPackageLabel = "Dooro Pakeejka Bixinta",
                digitalCopyLabel = "Koppiga Dijitaalka Ah (PDF/JPG - 50 ETB)",
                hardcopyLabel = "Waraaqda Hardcopy Ah (400 ETB)",
                submitBtn = "Dhiib Ccodsiga & Sii Bixinta",
                payNowBtn = "Xaqiiji Bixinta",
                viewCardBtn = "Eeg Kaadhka",
                filterAll = "Dhammaan",
                filterPending = "Sugaya",
                filterApproved = "La Ansixiyay",
                adminSwitchCustomer = "U Beddel Macmiilka",
                customerSwitchAdmin = "U Beddel Maamulka"
            )
            "en" -> AppUiLabels(
                appTitle = "Ethiopia ID Portal",
                subTitle = "Digital Resident ID Services",
                homeNav = "Home",
                newIdNav = "New ID / Renewal",
                paymentNav = "Payment Verification",
                previewNav = "ID Card Preview",
                adminNav = "Admin Console",
                qrNav = "QR Verification",
                notifNav = "Notifications",
                createNewIdBtn = "Apply For New Resident ID",
                selectLanguage = "Select Language",
                fullNameAmharicLabel = "Full Name (Regional Language)",
                fullNameEnglishLabel = "Full Name (English)",
                regionLabel = "Region",
                zoneSubCityLabel = "Zone / Sub City",
                woredaLabel = "Woreda",
                kebeleLabel = "Kebele",
                houseNoLabel = "House No.",
                phoneLabel = "Phone Number",
                emergencyContactLabel = "Emergency Contact Person",
                dobLabel = "Date of Birth",
                genderLabel = "Gender / Sex",
                bloodTypeLabel = "Blood Type",
                renewalDateLabel = "Renewal Issue Date",
                expiryRuleNotice = "Expiration date automatically calculated for +1 year.",
                selectPackageLabel = "Select ID Package Option",
                digitalCopyLabel = "Digital Softcopy (PDF/JPG - 50 ETB)",
                hardcopyLabel = "Printed PVC Card Printing (400 ETB)",
                submitBtn = "Submit Application & Pay",
                payNowBtn = "Confirm Payment",
                viewCardBtn = "View ID Card",
                filterAll = "All",
                filterPending = "Pending",
                filterApproved = "Approved",
                adminSwitchCustomer = "Switch to Customer",
                customerSwitchAdmin = "Switch to Admin"
            )
            else -> AppUiLabels( // Amharic 'am' default
                appTitle = "የኢትዮጵያ መታወቂያ",
                subTitle = "የዲጂታል መታወቂያ አገልግሎት",
                homeNav = "ዋና ገፅ",
                newIdNav = "አዲስ መታወቂያ / እድሳት",
                paymentNav = "የክፍያ ማረጋገጫ",
                previewNav = "የመታወቂያ ቅድመ-እይታ",
                adminNav = "የአስተዳደር መቆጣጠሪያ",
                qrNav = "የQR ኮድ ማረጋገጫ",
                notifNav = "መልዕክቶች",
                createNewIdBtn = "አዲስ የቀበሌ መታወቂያ አመልክት",
                selectLanguage = "ቋንቋ ይምረጡ",
                fullNameAmharicLabel = "ሙሉ ስም (በሀገር ውስጥ ቋንቋ)",
                fullNameEnglishLabel = "ሙሉ ስም (በእንግሊዝኛ)",
                regionLabel = "ክልል",
                zoneSubCityLabel = "ዞን / ክፍለ ከተማ",
                woredaLabel = "ወረዳ",
                kebeleLabel = "ቀበሌ",
                houseNoLabel = "የቤት ቁጥር",
                phoneLabel = "ስልክ ቁጥር",
                emergencyContactLabel = "የቅርብ ተጠሪ (ስም እና ስልክ)",
                dobLabel = "የትውልድ ቀን",
                genderLabel = "ፆታ",
                bloodTypeLabel = "የደም ዓይነት",
                renewalDateLabel = "የታደሰበት ቀን",
                expiryRuleNotice = "የሚያበቃበት ቀን በራስ-ሰር ለ1 ዓመት ይሰላል (+1 ዓመት ህግ)።",
                selectPackageLabel = "የአገልግሎት ፓኬጅ ይምረጡ",
                digitalCopyLabel = "ዲጂታል ኮፒ (PDF/JPG - 50 ETB)",
                hardcopyLabel = "የታተመ ፕላስቲክ ህትመት Hardcopy (400 ETB)",
                submitBtn = "አመልካች መረጃ ላክ እና ወደ ክፍሊት ሂድ",
                payNowBtn = "ክፍያውን አረጋግጥ",
                viewCardBtn = "መታወቂያውን ተመልከት",
                filterAll = "ሁሉም",
                filterPending = "በምርመራ ላይ",
                filterApproved = "የጸደቁ",
                adminSwitchCustomer = "ወደ ደንበኛ ገፅ ቀይር",
                customerSwitchAdmin = "ወደ አስተዳዳሪ ገፅ ቀይር"
            )
        }
    }
}
